### ISSUE TITLE
Help with BlockingIOError: [Errno 35] Resource temporarily unavailable

### ISSUE THREAD

**Issue by jestlin15** [s-andrews/sradownloader#23]
Hi, I have about 190 (x2 because of paired end) fastq files to download. However, I have faced the below issue twice when downloading: 

>  [ENA Attempt 1] Downloading ftp.sra.ebi.ac.uk/vol1/fastq/SRR314/003/SRR3140303/SRR3140303_1.fastq.gz into /Volumes/LaCie/S100A10/Fastq_files/GSE77509/fastq/SRR3140303_GSM2053449_N20_RNA-seq_Homo_sapiens_RNA-Seq_1.fastq.gz
> Exception in thread Thread-141 (background):
> Traceback (most recent call last):
>   File "/Users/j/miniconda3/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
>     self.run()
>   File "/Users/j/miniconda3/lib/python3.11/threading.py", line 975, in run
>     self._target(*self._args, **self._kwargs)
>   File "/Volumes/LaCie/sradownloader-3.11/sradownloader", line 142, in background
>     block = sock.recv(1024*1024)
>             ^^^^^^^^^^^^^^^^^^^^
> BlockingIOError: [Errno 35] Resource temporarily unavailable
> 

When I check when the SRR3140303_GSM2053449_N20_RNA-seq_Homo_sapiens_RNA-Seq_1.fastq.gz was last modified, it showed that it has been more than 24 hours. 

![image](https://github.com/s-andrews/sradownloader/assets/112469727/afc3b730-97dc-4d4b-a174-32da5a240260)

Would you suggest that I restarted the whole download again? Or wait it out? 

The first time this occurred, after waiting for a whole day, restarted my computer and I redownloaded all the datasets as I was not sure which files were downloaded and which files were not. 

Update: I restarted the downloads after clearing my internet history and cache. It seems to have gotten to attempt 3 but got stuck again: 

> [ENA] Downloading SRR3140303 into SRR3140303_GSM2053449_N20_RNA-seq_Homo_sapiens_RNA-Seq
> run_accession	fastq_ftp
> SRR3140303	ftp.sra.ebi.ac.uk/vol1/fastq/SRR314/003/SRR3140303/SRR3140303_1.fastq.gz;ftp.sra.ebi.ac.uk/vol1/fastq/SRR314/003/SRR3140303/SRR3140303_2.fastq.gz
> [ENA Attempt 1] Downloading ftp.sra.ebi.ac.uk/vol1/fastq/SRR314/003/SRR3140303/SRR3140303_1.fastq.gz into /Volumes/LaCie/S100A10/Fastq_files/GSE77509/fastq/SRR3140303_GSM2053449_N20_RNA-seq_Homo_sapiens_RNA-Seq_1.fastq.gz
> Exception in thread Thread-1 (background):
> Traceback (most recent call last):
>   File "/Users/j/miniconda3/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
>     self.run()
>   File "/Users/j/miniconda3/lib/python3.11/threading.py", line 975, in run
>     self._target(*self._args, **self._kwargs)
>   File "/Volumes/LaCie/sradownloader-3.11/sradownloader", line 142, in background
>     block = sock.recv(1024*1024)
>             ^^^^^^^^^^^^^^^^^^^^
> BlockingIOError: [Errno 35] Resource temporarily unavailable
> 426 Failure writing network stream.
> [ENA] Download failed for SRR3140303 - going around for another try
> [ENA Attempt 2] Downloading ftp.sra.ebi.ac.uk/vol1/fastq/SRR314/003/SRR3140303/SRR3140303_1.fastq.gz into /Volumes/LaCie/S100A10/Fastq_files/GSE77509/fastq/SRR3140303_GSM2053449_N20_RNA-seq_Homo_sapiens_RNA-Seq_1.fastq.gz
> Sleeping for 4 seconds before retrying
> 426 Failure writing network stream.
> [ENA] Download failed for SRR3140303 - going around for another try
> [ENA Attempt 3] Downloading ftp.sra.ebi.ac.uk/vol1/fastq/SRR314/003/SRR3140303/SRR3140303_1.fastq.gz into /Volumes/LaCie/S100A10/Fastq_files/GSE77509/fastq/SRR3140303_GSM2053449_N20_RNA-seq_Homo_sapiens_RNA-Seq_1.fastq.gz
> Sleeping for 9 seconds before retrying
> Exception in thread Thread-3 (background):
> Traceback (most recent call last):
>   File "/Users/j/miniconda3/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
>     self.run()
>   File "/Users/j/miniconda3/lib/python3.11/threading.py", line 975, in run
>     self._target(*self._args, **self._kwargs)
>   File "/Volumes/LaCie/sradownloader-3.11/sradownloader", line 142, in background
>     block = sock.recv(1024*1024)
>             ^^^^^^^^^^^^^^^^^^^^
> BlockingIOError: [Errno 35] Resource temporarily unavailable

2. In the scenario where it passes the BlockingIOError and goes to attempt5 and downloads from NCBI, is it possible to set for it to overwrite? I do not check the terminal all the time as it runs in the background hence when I leave it too long, it seems to just decide to not compress/overwrite. 

[ENA Attempt 5] Downloading ftp.sra.ebi.ac.uk/vol1/fastq/SRR314/000/SRR3140250/SRR3140250_1.fastq.gz into /Volumes/LaCie/S100A10/Fastq_files/GSE77509/fastq/SRR3140250_GSM2053438_N8_RNA-seq_Homo_sapiens_RNA-Seq_1.fastq.gz
Sleeping for 25 seconds before retrying
426 Failure writing network stream.
WARNING: Failed to download via ENA: [ENA] Download repeatedly failed for SRR3140250 - giving up trying NCBI instead
[NCBI] Downloading SRR3140250 into SRR3140250_GSM2053438_N8_RNA-seq_Homo_sapiens_RNA-Seq
[NCBI Attempt 1] Running: fasterq-dump --split-files --include-technical --threads 1 --temp /Volumes/LaCie/S100A10/Fastq_files/GSE77509/fastq --outfile SRR3140250_GSM2053438_N8_RNA-seq_Homo_sapiens_RNA-Seq.fastq --progress --outdir /Volumes/LaCie/S100A10/Fastq_files/GSE77509/fastq SRR3140250
join   :|-------------------------------------------------- 100%   
concat :|-------------------------------------------------- 100%   
spots read      : 12,894,974
reads read      : 25,789,948
reads written   : 25,789,948
Compressing /Volumes/LaCie/S100A10/Fastq_files/GSE77509/fastq/SRR3140250_GSM2053438_N8_RNA-seq_Homo_sapiens_RNA-Seq_1.fastq
/Volumes/LaCie/S100A10/Fastq_files/GSE77509/fastq/SRR3140250_GSM2053438_N8_RNA-seq_Homo_sapiens_RNA-Seq_1.fastq.gz already exists -- do you wish to overwrite (y or n)?

thank you.

**Comment by s-andrews** [comment]
Just going back through these.  The crash on ENA is an issue at their end.  We're doing the right thing in that we retry but we could maybe hide the stack trace.

The prompt to overwrite is a bug though we should just force that if there's an old copy lying around.
